Update launch scripts to include parameters for max sequences in a window and max sequences in a MSA

diff --git a/CONSENT-correct b/CONSENT-correct
--- a/CONSENT-correct
+++ b/CONSENT-correct
@@ -11,14 +11,15 @@ function print_help {
 	echo "	readsTechnology:               Indicate whether the long reads are from PacBio (--type PB) or Oxford Nanopore (--type ONT)"
 	echo ""
 	echo "	Options:"
-	echo "	--minSupport INT, -s INT:      Minimum support to consider a window for correction. (default: 4)"
-	echo "	--maxSupport INT, -S INT:      Maximum support to consider a window for correction. (default: 5,000)"
 	echo "	--windowSize INT, -l INT:      Size of the windows to process. (default: 500)"
+	echo "	--minSupport INT, -s INT:      Minimum support to consider a window for correction. (default: 4)"
+	echo "	--maxSupport INT, -S INT:      Maximum number of sequences to include into a window. (default: 1,000)"
+	echo "	--maxMSA INT, -M:              Maximum number of sequences to include into the MSA. (default: 150)"
 	echo "	--merSize INT, -k INT:         k-mer size for chaining and polishing. (default: 9)"
 	echo "	--solid INT, -f INT:           Minimum number of occurrences to consider a k-mer as solid during polishing. (default: 4)"
 	echo "	--anchorSupport INT, -c INT:   Minimum number of sequences supporting (Ai) - (Ai+1) to keep the two anchors in the chaining. (default: 8)"
 	echo "	--minAnchors INT, -a INT:      Minimum number of anchors in a window to allow consensus computation. (default: 10)"
-	echo "	--windowOverlap INT, -m INT:   Overlap size between consecutive windows. (default: 50)"
+	echo "	--windowOverlap INT, -o INT:   Overlap size between consecutive windows. (default: 50)"
 	echo "	--nproc INT, -j INT:           Number of processes to run in parallel (default: number of cores)."
 	echo "	--tmpdir STRING, -t STRING:    Path where to store the temporary overlaps file (default: working directory, as Alignments_dateTimeStamp.paf)."
 	echo "	--help, -h:                    Print this help message."
@@ -32,7 +33,8 @@ nproc=$(nproc)
 tmpdir="."
 out=""
 minSupport=4
-maxSupport=100000
+maxSupport=1000
+maxMSA=150
 windowSize=500
 merSize=9
 commonKMers=8
@@ -82,6 +84,11 @@ while [[ "$1" != "" ]] ; do
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) maxSupport="$2" ; shift 2 ;;
 			esac ;;
+		"--maxMSA"|"-M")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) maxMSA="$2" ; shift 2 ;;
+			esac ;;
 		"--windowSize"|"-l")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
@@ -107,7 +114,7 @@ while [[ "$1" != "" ]] ; do
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) solid="$2" ; shift 2 ;;
 			esac ;;
-		"--windowOverlap"|"-m")
+		"--windowOverlap"|"-o")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) windowOverlap="$2" ; shift 2 ;;
@@ -162,7 +169,7 @@ else
 fi
 
 echo "["$(date)"] Correcting the long reads"
-$LRSCf/bin/LRSelfCorrection -a $tmpdir/"$alignments" -s "$minSupport" -S "$maxSupport" -l "$windowSize" -k "$merSize" -c "$commonKMers" -A "$minAnchors" -f "$solid" -m "$windowOverlap" -j "$nproc" -r "$reads" >> "$out"
+$LRSCf/bin/LRSelfCorrection -a $tmpdir/"$alignments" -s "$minSupport" -S "$maxSupport" -l "$windowSize" -k "$merSize" -c "$commonKMers" -A "$minAnchors" -f "$solid" -m "$windowOverlap" -j "$nproc" -r "$reads" -M "$maxMSA" >> "$out"
 echo "["$(date)"] Removing the temporary files"
 rm $tmpdir/"$alignments"
 echo "["$(date)"] Exiting"
diff --git a/CONSENT-polish b/CONSENT-polish
--- a/CONSENT-polish
+++ b/CONSENT-polish
@@ -7,18 +7,19 @@ function print_help {
 	echo ""
 	echo "	Input:"
 	echo "	contigs.fasta:                 fasta file of contigs to polish, with one sequence per line."
-	echo "	longReads.fasta:                   fasta file of long reads to use for polishing, with one sequence per line."
+	echo "	longReads.fasta:               fasta file of long reads to use for polishing, with one sequence per line."
 	echo "	result.fasta:                  fasta file where to output the polished contigs."
 	echo ""
 	echo "	Options:"
-	echo "	--minSupport INT, -s INT:      Minimum support to consider a window for correction. (default: 4)"
-	echo "	--maxSupport INT, -S INT:      Maximum support to consider a window for correction. (default: 4)"
 	echo "	--windowSize INT, -l INT:      Size of the windows to process. (default: 500)"
+	echo "	--minSupport INT, -s INT:      Minimum support to consider a window for correction. (default: 4)"
+	echo "	--maxSupport INT, -S INT:      Maximum number of sequences to include into a window. (default: 1,000)"
+	echo "	--maxMSA INT, -M:              Maximum number of sequences to include into the MSA. (default: 150)"
 	echo "	--merSize INT, -k INT:         k-mer size for chaining and polishing. (default: 9)"
 	echo "	--solid INT, -f INT:           Minimum number of occurrences to consider a k-mer as solid during polishing. (default: 4)"
 	echo "	--anchorSupport INT, -c INT:   Minimum number of sequences supporting (Ai) - (Ai+1) to keep the two anchors in the chaining. (default: 8)"
 	echo "	--minAnchors INT, -a INT:      Minimum number of anchors in a window to allow consensus computation. (default: 10)"
-	echo "	--windowOverlap INT, -m INT:   Overlap size between consecutive windows. (default: 50)"
+	echo "	--windowOverlap INT, -o INT:   Overlap size between consecutive windows. (default: 50)"
 	echo "	--nproc INT, -j INT:           Number of processes to run in parallel (default: number of cores)."
 	echo "	--tmpdir STRING, -t STRING:    Path where to store the temporary overlaps file (default: working directory, as Alignments_dateTimeStamp.paf)."
 	echo "	--help, -h:                    Print this help message."
@@ -32,7 +33,8 @@ nproc=$(nproc)
 tmpdir="."
 out=""
 minSupport=4
-maxSupport=100000
+maxSupport=1000
+maxMSA=150
 windowSize=500
 merSize=9
 commonKMers=8
@@ -87,6 +89,11 @@ while [[ "$1" != "" ]] ; do
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) maxSupport="$2" ; shift 2 ;;
 			esac ;;
+		"--maxMSA"|"-M")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) maxMSA="$2" ; shift 2 ;;
+			esac ;;
 		"--windowSize"|"-l")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
@@ -112,7 +119,7 @@ while [[ "$1" != "" ]] ; do
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) solid="$2" ; shift 2 ;;
 			esac ;;
-		"--windowOverlap"|"-m")
+		"--windowOverlap"|"-o")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) windowOverlap="$2" ; shift 2 ;;
@@ -166,6 +173,6 @@ sort -k1 -T $tmpdir --parallel"$nproc" $tmpdir/"formatted_$alignments" > $tmpdir
 
 
 echo "["$(date)"] Polishing the contigs"
-$LRSCf/bin/LRSelfCorrection -a $tmpdir/"$alignments" -s "$minSupport" -S "$maxSupport" -l "$windowSize" -k "$merSize" -c "$commonKMers" -A "$minAnchors" -f "$solid" -m "$windowOverlap" -j "$nproc" -r "$contigs" -R "$reads" >> "$out"echo "["$(date)"] Removing the temporary files"
+$LRSCf/bin/LRSelfCorrection -a $tmpdir/"$alignments" -s "$minSupport" -S "$maxSupport" -l "$windowSize" -k "$merSize" -c "$commonKMers" -A "$minAnchors" -f "$solid" -m "$windowOverlap" -j "$nproc" -r "$contigs" -R "$reads" -M "$maxMSA" >> "$out"echo "["$(date)"] Removing the temporary files"
 rm $tmpdir/"$alignments"
 echo "["$(date)"] Exiting"
